# Generated by Django 4.0.5 on 2022-06-30 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_workexercise_workexercisedetails_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_color',
        ),
        migrations.RemoveField(
            model_name='workexercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workexercisedetails',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='workexercisedetails',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workexercisedetails',
            name='w_exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weights_lifted',
        ),
        migrations.AddField(
            model_name='workexercise',
            name='exercise_name',
            field=models.CharField(choices=[('BP', 'Bench Press'), ('S', 'Squat'), ('DL', 'Deadlift'), ('BR', 'Bench Row')], default='BP', max_length=2, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='workexercisedetails',
            name='rep_complete',
            field=models.IntegerField(blank=True, default='0', verbose_name='rep'),
        ),
        migrations.AddField(
            model_name='workexercisedetails',
            name='set_type',
            field=models.CharField(choices=[('work_set', 'work set'), ('warmup_set', 'warmup set')], default=None, max_length=11, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='workexercisedetails',
            name='workout_exercise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_details', to='testdb.workexercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='weights_lift',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='barbell_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='body_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='workexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', related_query_name='exercise_name', to='testdb.workout'),
        ),
        migrations.AlterField(
            model_name='workexercise',
            name='workset_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='workexercisedetails',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', related_query_name='weights_lift', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workout_exercise')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_images', to='testdb.workexercise')),
            ],
        ),
    ]
