# Generated by Django 4.0.5 on 2022-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_customuser_gender_alter_customuser_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexercise',
            name='exercise_name',
            field=models.CharField(choices=[('Bench Press', 'Bench Press'), ('Squat', 'Squat'), ('Deadlift', 'Deadlift'), ('Bench Row', 'Bench Row')], max_length=11, verbose_name='name'),
        ),
    ]
